[package]
name = "hentai-dl"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
reqwest = "0.13"
scraper = "0.25"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }
zip = "8"
